 ### Cargamos los datos del archivo games

In [19]:
import pandas as pd
import gzip
import json

In [20]:
steam_games = "../DataSets/steam_games.json.gz"

In [21]:
datos_games = []
with gzip.open(steam_games, 'rt', encoding='utf-8') as archivo_games:
    for linea in archivo_games:
        diccionario_linea_games = json.loads(linea)
        datos_games.append(diccionario_linea_games)
df_games = pd.DataFrame(datos_games)
df_games.head()

,publisher,genres,app_name,title,url,release_date,tags,reviews_url,specs,price,early_access,id,developer
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
columnas_deseadas = ['id', 'genres', 'app_name', 'release_date']
df_games = df_games[columnas_deseadas]

In [23]:
df_games = df_games.dropna()

In [24]:
df_games_desa = df_games.explode('genres')

In [25]:
df_desanidado = df_games_desa.reset_index(drop=True)

In [26]:
df_sampled = df_desanidado.sample(frac=0.1, random_state=42)
df_sampled.to_csv('../DataSets/df_games_id.csv',index=False)

In [28]:
df_sampled

,id,genres,app_name,release_date
23662,683570,Adventure,Cludbugz's Twisted Magic,2017-08-04
31544,585900,Adventure,Harvest Moon: Light of Hope,2017-11-14
62163,297270,Strategy,Exodus Wars: Fractured Empire,2015-01-30
64347,321182,Design &amp; Illustration,RPG Maker VX Ace - Dungeon Music Pack,2014-09-16
21261,614910,Casual,#monstercakes,2017-05-05
...,...,...,...,...
12141,236870,Action,HITMAN™,2016-03-11
57222,378474,Action,SW4-II - Horse Set,2015-09-29
277,19200,Action,Tank Universal,2008-08-21
5510,325180,Software Training,AppGameKit: Easy Game Development,2014-11-21
5740,207140,Indie,SpeedRunners,2016-04-19